services:
  - type: web
    name: optimeyes-backend
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: OPENROUTER_API_KEY
        sync: false
